
# Do not change here, just use /setup command.
changes:
  x1: 0
  x2: 0
  y1: 0
  y2: 0
  z1: 0
  z2: 0

delete:
  time: 10 #seconds

no-space: '&7There is not enough space: {lun}x{lat}x{ina}'
create-ground: '&7You need to create the base on ground.'

error: '&cOOPS! Something went wrong, please contact an administrator'

cannot-interact: '&7You cannot interact on this base because it s not your base.'
position:
  first: '&aFirst position was set up'
  second: '&aSecond position was set up'
  saved: '&aYou saved the region'
  error: '&cYou did not defined the region, use the netherite axe to do it.'

start: '&aNow you are in the setup position, use the axe to define the region of this build, and use the emerald to save it. To exit, use /setup exit'

items:
  axe:
    name: '&aRegion cover axe'
    lore:
      - '&aRight Click to set the first position.'
      - '&aLeft Click to set the second position.'
  emerald:
    name: '&aSave'
    lore:
      - 'Right click on a block to save the region.'
left: '&7You have left the setup mode.'
no-permission: '&cYou do not have permission to use this command.'
no-console: 'This command can be used only by a player.'
already-have-base: 'You already have a base on: x: {x}, y: {y}, z: {z} in {world}'
inventory:
  manage: 'Manage your base'
  manage-items:
    delete: '&cDelete your base'
    manage: '&6Manage your member list'
    close: '&cClose'
  members: 'Members'
  members-items:
    add: '&aAdd a new member'
    remove: '&cRemove a member'
    close: '&cClose'
remove-a-member: '&7Send in chat the number of player that you want to remove from your team or type cancel to cancel de action.'
add-a-member: '&7Send in chat the name of player that you want to add in your team, it needs to be online.'
he-was-added: '{name} was added in your base'
add-error: '{name} is already added in your base.'
add-error-2: '{name} is not online, you can''t add him'
remove-success: 'You removed him'
no-number: 'You need to send a number'
number-above: 'You need to send a number from above'
first-page: '&7You are already on the first page.'
left-button: '&aLeft'
last-page: '&7You are on the last page.'
right-button: '&aRight'
close-button: '&cClose'
add-members:
  title: '&7List of your base members'
  successfully: '&aYou added {player}.'
  item:
    name: '&a{player}'
    lore:
      - '&aLeft Click to add {name}'
      - '&ain your team.'

remove-member:
  list:
    title: '&7List of your base members'
    item:
      name: '&a{player}'
      lore:
        - '&aLeft Click to remove {name}'
        - '&afrom your team.'
  confirm:
    title: '&aRemove {name}'
    da:
      name: '&bYes'
      lore:
        - '&aWould you really want to'
        - '&aremove {name} from your team?'
    nu:
      name: '&cNo'
    successfully: '&aYou removed {player}.'
no-distance: '&cYou must have a distance of at least 20 blocks between the base.'